### ISSUE TITLE
When will this get PR'd into burn?

### ISSUE THREAD

**Issue by Khaled-Ayman1** [VlaDexa/burn-efficient-kan#1]
I stumbled upon this repo at 4 am. Couldn't believe to see rust implementation this fast haha.

If I may ask how much work is left before merging into burn?

Expect future PRs from my team ;)

**Comment by VlaDexa** [comment]
Hi!
This repo was created more as a little research project on ML situation in Rust, and I didn't even know that it could be accepted into burn.
Right now the problems I see with the implementation are:
- The least squares algorithm is implemented using `ndarray` so it has to copy from device buffer to `ndarray` structure and do that on CPU always, which I assume is slow, and the proper way to do this would be to write a kernel
- I have no idea if [the originating Python code](https://github.com/Blealtan/efficient-kan) (which this repo adapts into burn) is even correct implementation of KAN.
- Mnist example in the python implementation uses exponential learning rate, but when I plug it into my example, it just stops getting validation percent higher that 60% or so, and I have no idea why, and since I'm don't have much knowledge on ML I feel like I can't know why.

**Comment by Khaled-Ayman1** [comment]
Thanks for your response and for outlining the challenges. My team and I plan to build on the solid foundation you've laid here and make contributions to this repo soon enough. We're specifically focusing on adopting KAN instead of MLPs in various applications and we'd like to experiment if Rust would tackle some of its controversial drawbacks.

Expect to see future PRs from us as we progress!
